### ISSUE TITLE
Create contact form

### ISSUE THREAD

**Issue by mezzoblue** [styleandclass/styleandclass.ca#3]
We want /contact/ to actually have a form and ways of getting in touch with us, including:
- email address
- Twitter handle
- Meetup link

Having done zero research on this, I'd imagine the challenge here will be doing something with a form on a static site that has no back end.

**Comment by stevemynett** [comment]
(I haven't had experience using them) but many static site generators suggest [Wufoo](http://www.wufoo.com/) which should work without any server site stuffs.
